### ISSUE TITLE
`C-g` doesn't abort operation when running `tree-sitter-ispell-run-buffer`

### ISSUE THREAD

**Issue by gopar** [erickgnavar/tree-sitter-ispell.el#2]
Thanks for the package :)

**Comment by erickgnavar** [comment]
Hi, the way how it is implemented make an `ispell-region` call for every text node in the buffer, `C-g` it's aborting the operation but only one at time.

For example if the buffer have 3 text nodes if will run `ispell-region` 3 times and you will need to press `C-g` 3 times as well to abort `ispell` process.

Maybe an option could be to add a specific function to cancel the whole process, I'll think about something to solve this, I hope the package is being useful to you :)
